image:
  file: .gitpod.Dockerfile

ports:
- port: 8100
  onOpen: open-preview
tasks:
- before: export ROOT_URL=$(gp url 8100)
  init: >
    python -m pip install -r requirements.txt 
  command: >
    python runserver.py
