image:
  file: .gitpod.Dockerfile

ports:
- port: 8100
  onOpen: open-preview
tasks:
- before: |
    export FLASK_APP=runserver.py
- name: pip
  init: >
    python -m pip install --upgrade pip
    gp sync-done pip
  command: pip install flask

- name: requirements
  init: >
    gp sync-await pip
  command: >
    python -m pip install -r requirements.txt 

- name: server
  init: >
    gp sync-await pip
  command: >
    flask run -h 0.0.0.0 -p 8100    
